# ===========================================================
# NAVIGATION
# ===========================================================

nav:
  - Home: README.md
  - My apps: pages/my-apps.md
  - Docs: https://docs.alnoda.org/ansible-terraform-workspace/


# ===========================================================
# CONFIGURATION
# ===========================================================

site_name: Infra Workspace
repo_url: https://github.com/bluxmit/alnoda-workspaces
site_url: https://docs.alnoda.org
edit_uri: ""

# ===========================================================
# APPEARANCE
# ===========================================================

theme:
  name: 'material'
  favicon: 'assets/favicon.ico'
  logo: 'assets/Alnoda-logo.svg'
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.instant
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
      primary: red  
      accent: orange
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: red
      accent: orange

extra:
  # Link to open when your logo is clicked
  homepage: https://docs.alnoda.org
  host_url: http://docs.alnoda.org

plugins:
  - search
  # Enable Macros and jinja2 templates
  - macros:
      module_name: macros/helpers


extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6




          
 



